name: Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
    deploy:
        name: deploy lambda function
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: AWS Lambda Deploy
          uses: appleboy/lambda-action@v0.1.9
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: 'eu-west-2'
            function_name: terraform-func
            zip_file: 'aws-infra/packedlamda.zip'
            
          


